<?php

use Illuminate\Support\Facades\Route;

Route::prefix('admin')->group(function(){
    Route::get('',[
        'as'=>'admins.index',
        'uses'=>'Admins\AdminController@index'
    ]);

    Route::prefix('category')->group(function(){
        Route::get('',[
            'as'=>'category.index',
            'uses'=>'Admins\CategoryController@index'
        ]);
        Route::get('create',[
            'as'=>'category.create',
            'uses'=>'Admins\CategoryController@create'
        ]);
        Route::post('store',[
            'as'=>'category.store',
            'uses'=>'Admins\CategoryController@store'
        ]);
        Route::get('edits/{id}',[
            'as'=>'category.edits',
            'uses'=>'Admins\CategoryController@edits'
        ]);
        Route::post('update/{id}',[
            'as'=>'category.update',
            'uses'=>'Admins\CategoryController@update'
        ]);
        Route::get('edit/{id}',[
            'as'=>'category.delete',
            'uses'=>'Admins\CategoryController@delete'
        ]);
    });

    Route::prefix('brand')->group(function(){
        Route::get('',[
            'as'=>'brand.index',
            'uses'=>'Admins\BrandController@index'
        ]);
        Route::get('create',[
            'as'=>'brand.create',
            'uses'=>'Admins\BrandController@create'
        ]);
        Route::post('store',[
            'as'=>'brand.store',
            'uses'=>'Admins\BrandController@store'
        ]);
        Route::get('edits/{id}',[
            'as'=>'brand.edits',
            'uses'=>'Admins\BrandController@edits'
        ]);
        Route::post('update/{id}',[
            'as'=>'brand.update',
            'uses'=>'Admins\BrandController@update'
        ]);
        Route::get('edit/{id}',[
            'as'=>'brand.delete',
            'uses'=>'Admins\BrandController@delete'
        ]);
    });
});
